#pragma once

#define DBG(txt) COLORIZE(FA_DEFAULT, FG_GRAY, BG_DEFAULT, "[DBG] " txt, RST_ALL)
#define DBG_START COLOR_START(FA_DEFAULT, FG_GRAY, BG_DEFAULT) "[DBG] "
#define DBG_END COLOR_END(RST_ALL)

#define EVT(txt) COLORIZE(FA_DEFAULT, FG_SET24(42, 90, 90), BG_DEFAULT, "[EVT] " txt, RST_ALL)